### ISSUE TITLE
编译报错，缺少两个包，手工添加如下就正常了！

### ISSUE THREAD

**Issue by bluesky129** [xuxueli/xxl-api#15]
<dependency>
			<groupId>commons-collections</groupId>
			<artifactId>commons-collections</artifactId>
			<version>3.2.1</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.3.2</version>
		</dependency>

**Comment by xuxueli** [comment]
你好，感谢反馈！
问题无法复现，可下载最新版本重新编译，或者进一步提供复现条件。
