### ISSUE TITLE
请求头部是不是要增加自定义

### ISSUE THREAD

**Issue by 18916204759** [xuxueli/xxl-api#19]
有些Api可能需要自定义一些请求头，目前项目里面没看看见自定义的方法，希望可以添加

**Comment by xuxueli** [comment]
你好，感谢反馈！
该需求已经加入TODO，将会排期处理。

**Comment by xuxueli** [comment]
本文为重复ISSUE，最新进展可查看：https://github.com/xuxueli/xxl-api/issues/13
