### ISSUE TITLE
保存新的接口之前添加测试该接口的按钮并显示返回的内容

### ISSUE THREAD

**Issue by abdushkur** [xuxueli/xxl-api#21]
保存新的接口之前添加测试该接口的按钮并显示返回的内容
第二个要说的是 在接口列表中增加“测试接口”按钮，少一步进入接口详情页面再点击“接口测试”

**Comment by xuxueli** [comment]
您好，感谢反馈！
第一条建议仍在讨论确定中。
第二条建议已经推送到master分支，可前往查看。
