### ISSUE TITLE
requestbody请求的问题

### ISSUE THREAD

**Issue by phphappy** [xuxueli/xxl-api#24]
在测试使用过程中发现无request body输入项，建议加上requestbody的输入项

**Comment by zhangyq1011** [comment]
我也有同样的建议。

**Comment by ZHAO163168** [comment]
是不是post方式无法提交到后台呀？

**Comment by ZHAO163168** [comment]
用这个进行测试，发现post方式，提交到后台，json转换失败，而我用postman进行测试，正常

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-api/issues/3

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-api/issues/3
