### ISSUE TITLE
get 地址转换错误

### ISSUE THREAD

**Issue by gufeng710** [xuxueli/xxl-api#26]
XxlApiTestController.java中218行
finalUrl测试值为http://localhost:8084/dataCollection/qryBusinessData?cityCode=531&dateSelect=1&
截取后http://localhost:8084/dataCollection/qryBusinessData?cityCode=531&dateSelect=

**Comment by SpringStudent** [comment]
![image](https://user-images.githubusercontent.com/14833956/37317662-22f0d8f8-26a1-11e8-9af8-ea7e2064e17a.png)
这里改为-1

**Comment by xuxueli** [comment]
你好，感谢关注与反馈！
该问题已经修复并推送master，可以前往查看。
