### ISSUE TITLE
关于升级后数据库更新的问题

### ISSUE THREAD

**Issue by mojie126** [xuxueli/xxl-api#27]
每次升级后数据库不需要更新的么...？
比如我之前是1.0.1，这次升级到1.1.0，数据库如何不删除原库更新的...？还是说数据库不需要更新...？

**Comment by xuxueli** [comment]
你好，v1.1.0 升级对表结构做了变更。可以对比下两个版本的建表SQL，部分表结构做了部分字段调整需要调整现有表结构，同时也新增了部分新表需要初始化。（调整前，建议先DB备份）
然后，可以编译部署新版，复用调整后的表数据。

**Comment by mojie126** [comment]
嗯...那为啥不给一个upgrade.sql呢...

**Comment by xuxueli** [comment]
各版本比较多，都提供的话工作量比较大哈，可以自行对比建表SQL调整。表变更较小，调整很少的。
