### ISSUE TITLE
希望增加Json格式的RequestBody以及Json格式展示时不要用text，且能格式化显示，高亮显示

### ISSUE THREAD

**Issue by mulhyac** [xuxueli/xxl-api#31]

**Comment by ZHAO163168** [comment]
你好， 请问怎么增加json格式的RequestBody？

**Comment by ZHAO163168** [comment]
我用post方式提交到微服务后台，后台报 json转换失败，前台报404错误，请求头里面已经设置了 content-Type=application/json，应该怎么处理呢

**Comment by 7010G** [comment]
> _No description provided._

在我的分支已经做了改进哦

**Comment by xuxueli** [comment]
合并至： https://github.com/xuxueli/xxl-api/issues/3
