### ISSUE TITLE
对于响应状态码为302的请求未能正确展示“Location”

### ISSUE THREAD

**Issue by tianling11025** [xuxueli/xxl-api#36]
如图所示，状态码为302，Header中的Location字段未正确显示：
![image](https://user-images.githubusercontent.com/16515823/47343625-17c78880-d6d9-11e8-830e-3c7544b6dbb0.png)
检查发现`com.xxl.api.admin.controller.XxlApiTestController`中获取header方法错误

```java
if (statusCode == 302) {
   responseContent += "；Redirect地址：" + response.getHeaders("Location");
}
```
替换为：
```java
if (statusCode == 302) {
   responseContent += "；Redirect地址：" + response.getFirstHeader("Location").getValue();
}
```

**Comment by xuxueli** [comment]
感谢反馈，已合并至master，将跟随下个版本一同发布；
