### ISSUE TITLE
建议开发类似swagger的接口文档注解，启动自动上报到文档中心，省去文档中心管理平台人工一个一个录入

### ISSUE THREAD

**Issue by WYongLin** [xuxueli/xxl-api#39]
建议开发类似swagger的接口文档注解，微服务配置一个文档中心的地址、项目编码等参数，启动自动上报到文档中心，省去文档中心管理平台人工一个一个录入。  
 就像dubbo rpc接口自动注册到注册中心一样。
这样开发人员只用创建项目分组等信息即可。

**Comment by 7010G** [comment]
同感

**Comment by 7010G** [comment]
> 楼上提到的这个工具，我正在做哈，所以才关注了码主的项目：https://www.bywei.cn/post/961.html

机器人？？

**Comment by bywei** [comment]
> > 楼上提到的这个工具，我正在做哈，所以才关注了码主的项目：https://www.bywei.cn/post/961.html
> 
> 机器人？？

我是么？

**Comment by 7010G** [comment]
> > > 楼上提到的这个工具，我正在做哈，所以才关注了码主的项目：https://www.bywei.cn/post/961.html
> > 
> > 
> > 机器人？？
> 
> 我是么？

现在看起来不是哦

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-api/issues/20
