### ISSUE TITLE
类型转化错误 bug

### ISSUE THREAD

**Issue by th8664484** [xuxueli/xxl-api#60]
jdk1.8
IDEA

com/xxl/api/admin/core/util/JacksonUtil.java

readValueRefer方法返回值类型转化失败。
        return getInstance().readValue(jsonStr, typeReference);
java: 不兼容的类型: java.lang.Object无法转换为T

解决：
return (T)getInstance().readValue(jsonStr, typeReference);

**Comment by david0718** [comment]
nice 兄弟~~~~给你点赞

**Comment by xuxueli** [comment]
已修复，本周发布
